server:
  port: 8000

spring:
  application:
    name: canteen-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/canteen_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379
      password: "123456"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: canteen-token
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: true
  jwt-secret-key: canteen-jwt-secret-key-2024

system:
  is-mock-sms: true
